#!/bin/bash
# DEPLOY.sh - Manual Deployment Script

echo "=========================================="
echo "🚀 UNIVERSAL CRM DEPLOYMENT SCRIPT"
echo "=========================================="
echo ""

cd "$(dirname "$0")"

echo "📁 Deploy directory: $(pwd)"
echo ""

# Check if firebase is logged in
echo "🔑 Checking Firebase authentication..."
firebase login:list 2>/dev/null || echo "Not logged in"

echo ""
echo "📝 To deploy, you need to:"
echo ""
echo "1. Run: firebase login"
echo "2. Then run: firebase deploy --only hosting --project wasi-app-1"
echo ""
echo "OR run this command directly:"
echo ""
echo "   firebase deploy --only hosting --project wasi-app-1"
echo ""
echo "=========================================="
echo "🔐 AUTHENTICATION & ROLE SETUP:"
echo "=========================================="
echo "   Roles are now restricted for security!"
echo ""
echo "   SELF-SIGNUP (No code needed):"
echo "   • Customer - Click 'Create Account' → Select 'Customer / Client'"
echo "   • Agent - Click 'Create Account' → Select 'Agent / Team Member'"
echo ""
echo "   REQUIRES INVITATION CODE:"
echo "   • Admin - Use code: ADMIN2024"
echo "   • Master Admin - Use code: MASTER2024"
echo ""
echo "   📚 See AUTH_SETUP.md for detailed instructions"
echo ""
echo "🔗 PORTAL URLs:"
echo "=========================================="
echo "   Sign In / Sign Up: https://wasi-app-1.web.app/"
echo "   Customer Portal: https://wasi-app-1.web.app/customer"
echo "   Agent Portal: https://wasi-app-1.web.app/agent"
echo "   Admin Portal: https://wasi-app-1.web.app/admin"
echo "   Master Portal: https://wasi-app-1.web.app/master"
echo "=========================================="
