#!/bin/bash
# GitHub Setup Helper Script

echo "=========================================="
echo "🚀 GitHub Setup Helper"
echo "=========================================="
echo ""

echo "📋 STEPS TO SETUP GITHUB AUTO-DEPLOY:"
echo ""
echo "1. Create GitHub Repository:"
echo "   → https://github.com/new"
echo "   → Name: universal-crm"
echo "   → Click 'Create repository'"
echo ""
echo "2. Run these commands:"
echo ""
echo "   git init"
echo "   git add ."
echo "   git commit -m 'Initial commit'"
echo "   git branch -M main"
echo "   git remote add origin https://github.com/YOUR_USERNAME/universal-crm.git"
echo "   git push -u origin main"
echo ""
echo "3. Add Firebase Secret:"
echo "   → Go to: https://console.firebase.google.com/project/wasi-app-1/settings/serviceaccounts/adminsdk"
echo "   → Click 'Generate new private key'"
echo "   → Download JSON file"
echo "   → Go to GitHub repo → Settings → Secrets → Actions"
echo "   → New secret: FIREBASE_SERVICE_ACCOUNT_WASI_APP_1"
echo "   → Paste JSON content"
echo ""
echo "4. That's it! Push to main branch will auto-deploy!"
echo ""
echo "=========================================="
echo "📖 Full guide: GITHUB_SETUP.md"
echo "=========================================="
