/* AUTOGENERATED FILE - Env vars override defaults below */

// Fallback defaults (used if env vars not set)
const DEFAULT_PROJECT_ID = "xtisrggenkbazqziefnl";
const DEFAULT_PUBLIC_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0aXNyZ2dlbmtiYXpxemllZm5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxMTY4NTQsImV4cCI6MjA4NzY5Mjg1NH0.M93k4udmY2muiNhLM-BI_Ys3KeQSeJIWbcBADSICEdo";

/**
 * Supabase Project ID
 * Override via: VITE_SUPABASE_PROJECT_ID env variable
 */
export const projectId = (import.meta.env.VITE_SUPABASE_PROJECT_ID as string) || DEFAULT_PROJECT_ID;

/**
 * Supabase Public Anon Key
 * Override via: VITE_SUPABASE_ANON_KEY env variable
 */
export const publicAnonKey = (import.meta.env.VITE_SUPABASE_ANON_KEY as string) || DEFAULT_PUBLIC_ANON_KEY;